// <auto-generated />
namespace wajeb004.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class class_code : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(class_code));
        
        string IMigrationMetadata.Id
        {
            get { return "202002280147167_class_code"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
