// <auto-generated />
namespace wajeb004.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class questionSequence : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(questionSequence));
        
        string IMigrationMetadata.Id
        {
            get { return "202003100500162_questionSequence"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
