// <auto-generated />
namespace wajeb004.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class quizzs_with_answersnapshots : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(quizzs_with_answersnapshots));
        
        string IMigrationMetadata.Id
        {
            get { return "202003050404503_quizzs_with_answersnapshots"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
